apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ .Release.Name }}-http-server"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/component: http-server
    {{- include "kuard.metadataLabels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: http-server
      {{- include "kuard.selectorLabels" $ | nindent 6 }}
  namespaceSelector:
    matchNames:
      - "{{ .Release.Namespace }}"
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
