resources:
  requests:
    cpu: 1m
    memory: 1Mi
  limits: {}
webhook:
  resources:
    requests:
      cpu: 1m
      memory: 1Mi
    limits: {}
cainjector:
  resources:
    requests:
      cpu: 1m
      memory: 1Mi
    limits: {}
startupapicheck:
  resources:
    requests:
      cpu: 1m
      memory: 1Mi
    limits: {}
