resources:
  requests:
    cpu: 1m
    memory: 1Mi
  limits: {}
kubectl:
  resources:
    requests:
      cpu: 1m
      memory: 1Mi
    limits: {}
nodeAgent:
  resources:
    requests:
      cpu: 1m
      memory: 1Mi
    limits: {}
