apiVersion: v2
name: undefined
version: 0.0.0
dependencies:
  - # https://github.com/cert-manager/cert-manager/tree/master/deploy/charts/cert-manager
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v1.17.1
  - # https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-operator-crds
    repository: https://prometheus-community.github.io/helm-charts
    name: prometheus-operator-crds
    version: 18.0.1
