apiVersion: v2
name: undefined
version: 0.0.0
dependencies:
  - # https://github.com/cert-manager/cert-manager/tree/master/deploy/charts/cert-manager
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v1.17.1
  - # https://github.com/cilium/cilium/tree/main/install/kubernetes/cilium
    repository: https://helm.cilium.io
    name: cilium
    version: 1.17.2
  - # https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-operator-crds
    repository: https://prometheus-community.github.io/helm-charts
    name: prometheus-operator-crds
    version: 18.0.1
  - # https://github.com/vmware-tanzu/helm-charts/tree/main/charts/velero
    repository: https://vmware-tanzu.github.io/helm-charts
    name: velero
    version: 8.5.0
