apiVersion: v2
name: postgres
version: 0.9.100
dependencies:
  - # PROD repository: oci://europe-central2-docker.pkg.dev/gogcp-main-9/private-helm-charts/gorun/core
    repository: file://../configs
    name: configs
    version: 0.9.100
