repository: europe-central2-docker.pkg.dev/gogcp-main-9/private-docker-images/gorun/core/devcontainer
tag: 0.9.101
aliases:
  # https://hub.docker.com/r/damlys/gorun-devcontainer
  - repository: damlys/gorun-devcontainer
