repository: europe-central2-docker.pkg.dev/gogcp-main-2/private-docker-images/gorun/core/devcontainer
tag: 0.2.100
aliases:
  - # https://hub.docker.com/r/damlys/gorun-devcontainer
    repository: damlys/gorun-devcontainer
  - # https://github.com/users/damlys/packages/container/package/gogcp-devcontainer
    repository: ghcr.io/damlys/gorun-devcontainer
