repository: europe-central2-docker.pkg.dev/gogke-main-0/private-docker-images/gogke/core/devcontainer
tag: 0.2.3
aliases:
  - # https://hub.docker.com/r/damlys/gogcp-devcontainer
    repository: damlys/gogcp-devcontainer
  - # https://github.com/users/damlys/packages/container/package/gogcp-devcontainer
    repository: ghcr.io/damlys/gogcp-devcontainer
