apiVersion: v2
name: undefined
version: 0.0.0
dependencies:
  - # https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-state-metrics
    repository: https://prometheus-community.github.io/helm-charts
    name: kube-state-metrics
    version: 5.31.0
  - # https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-blackbox-exporter
    repository: https://prometheus-community.github.io/helm-charts
    name: prometheus-blackbox-exporter
    version: 9.4.0
  - # https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-node-exporter
    repository: https://prometheus-community.github.io/helm-charts
    name: prometheus-node-exporter
    version: 4.45.0
