#!/bin/bash
set -e

function main {
  local kubeconfig="${HOME}/workspace/docker-desktop-kubeconfig.yaml"
  kubectl --context="docker-desktop" config view --raw --minify >"$kubeconfig"
  kubectl --kubeconfig="$kubeconfig" --context="docker-desktop" config set-cluster "docker-desktop" --server="https://kubernetes.docker.internal:6443"
}

main "$@"
