# https://hub.docker.com/r/grafana/grafana
image:
  repository: europe-central2-docker.pkg.dev/gogcp-main-8/private-docker-images/gorun/o11y/grafana
  tag: 0.8.100

configEnvs: {}
secretConfigEnvs: {}
configFiles: {}
secretConfigFiles: {}

serviceAccountName: ""
extraPodLabels: {}
extraPodAnnotations: {}
extraServiceLabels: {}
extraServiceAnnotations: {}
minReplicas: 1
maxReplicas: 1
maxUnavailable: 1
resources:
  requests:
    cpu: 1m
    memory: 1Mi
  limits:
    cpu: 1000m
    memory: 1Gi
