schemaVersion: 2.0.0
fileExistenceTests:
  - name: nginx.conf file
    path: /etc/nginx/nginx.conf
    shouldExist: true
  - name: index.html file
    path: /usr/share/nginx/html/index.html
    shouldExist: true
fileContentTests:
  - name: nginx group
    path: /etc/group
    expectedContents:
      - .*nginx:x:101:.*
  - name: nginx user
    path: /etc/passwd
    expectedContents:
      - .*nginx:x:101:101:nginx user,,,:/nonexistent:/bin/false.*
metadataTest:
  user: root:root
  workdir: /
  volumes: []
  exposedPorts: ["80"]
  entrypoint: []
  cmd: ["nginx"]
