#!/bin/bash
set -e
for lib in "$(dirname "$0")"/lib/*.bash; do source "${lib}"; done

function main {
  local cmd="$1"
  local project_path="$2"
  local project_scope
  local project_name
  local chart_repository
  local chart_name
  local chart_version

  project_scope="$(echo "${project_path}" | cut -d '/' -f 2)"
  project_name="$(echo "${project_path}" | cut -d '/' -f 4)"

  chart_repository="$(yq '.repository' "${project_path}/.project.yaml")"
  chart_name="$(yq '.name' "${project_path}/Chart.yaml")"
  chart_version="$(yq '.version' "${project_path}/Chart.yaml")"

  case "${cmd}" in
  "build")
    helm package "${project_path}" --destination="${project_path}/.."
    ;;

  "test")
    if ! str::ends_with "${chart_repository}/${chart_name}" "/${project_scope}/${project_name}"; then
      log::error "chart does not match naming convention: ${project_path}"
      return 1
    fi
    if ! semver::validate "${chart_version}"; then
      log::error "chart version is not a valid SemVer number: ${project_path}"
      return 1
    fi
    helm lint "${project_path}"
    ;;

  "pre-publish")
    if ! file::exists "${project_path}/CHANGELOG.md"; then
      log::error "changelog file does not exists: ${project_path}"
      return 1
    fi
    if ! changelog::contains_version "${project_path}" "${chart_version}"; then
      log::warning "changelog does not contain header with the chart version: ${project_path}"
    fi
    if git::tag_exists "${project_path}/v${chart_version}"; then
      log::error "git tag with chart version already exists: ${chart_version}"
      log::info "bump chart version to fix the issue: ${project_path}"
      return 1
    fi
    ;;

  "publish")
    git::tag "${project_path}/v${chart_version}"
    helm push "${project_path}-${chart_version}.tgz" "${chart_repository}"
    ;;

  "show")
    echo "helm pull \"${chart_repository}/${chart_name}\" --version=\"${chart_version}\""
    ;;

  *)
    log::error "unknown command: ${cmd}"
    return 127
    ;;
  esac
}

main "$@"
