#!/bin/bash
set -e
for lib in "$(dirname "$0")"/lib/*.bash; do source "${lib}"; done

function main {
  # render GitHub Actions workflows
  rm -f ./.github/workflows/workflow.*.gotmpl.yaml
  go run ./go/cmd/render-github-workflows

  # render GitLab pipelines
  rm -f ./.gitlab-ci.yml
  go run ./go/cmd/render-gitlab-pipelines

  # render Bitbucket pipelines
  rm -f ./bitbucket-pipelines.yml
  go run ./go/cmd/render-bitbucket-pipelines

  # apply Google Cloud Build builds
  terraform -chdir="projects/cicd/terraform-modules/cloud-build" apply -auto-approve
}

main "$@"
