#!/bin/bash
set -e
for lib in "$(dirname "$0")"/lib/*.bash; do source "${lib}"; done

function main {
  rm -f ./.github/workflows/workflow.*.gotmpl.yaml
  go run ./go/cmd/render-github-workflows
}

main "$@"
