#!/bin/bash
set -e
for lib in "$(dirname "$0")"/lib/*.bash; do source "${lib}"; done

function main {
  rm -f ./.gitlab-ci.yml
  go run ./projects/core/go-modules/monorepo/cmd/render-gitlab-pipelines
}

main "$@"
