#!/bin/bash
set -e
for lib in "$(dirname "$0")"/lib/*.bash; do source "${lib}"; done

function main {
  local cmd="$1"
  local project_path="$2"
  local backend_prefix

  backend_prefix="$(hclq get --raw 'terraform.backend.gcs.prefix' --in="${project_path}/terraform.tf")"

  case "${cmd}" in
  "test")
    if ! str::ends_with "${backend_prefix}" "${project_path}"; then
      log::error "terraform backend does not match naming convention: ${project_path}"
      return 1
    fi
    terraform -chdir="${project_path}" fmt -check -recursive .
    terraform -chdir="${project_path}" init -input=false
    terraform -chdir="${project_path}" validate
    ;;

  "plan")
    terraform -chdir="${project_path}" init -input=false
    terraform -chdir="${project_path}" plan -input=false
    ;;

  "apply")
    terraform -chdir="${project_path}" init -input=false
    terraform -chdir="${project_path}" apply -input=false -auto-approve
    ;;

  *)
    log::error "unknown command: ${cmd}"
    return 127
    ;;
  esac
}

main "$@"
