name: projects/o11y/terraform-submodules/gke-lgtm-stack
on:
  pull_request:
    paths:
      - "projects/o11y/terraform-submodules/gke-lgtm-stack/**"
      - "!projects/o11y/terraform-submodules/gke-lgtm-stack/README.md"
  push:
    branches:
      - main
    paths:
      - "projects/o11y/terraform-submodules/gke-lgtm-stack/**"
      - "!projects/o11y/terraform-submodules/gke-lgtm-stack/README.md"
jobs:
  projects-o11y-terraform-submodules-gke-lgtm-stack:
    name: projects/o11y/terraform-submodules/gke-lgtm-stack
    runs-on: ubuntu-24.04
    container: ghcr.io/damlys/gorun-devcontainer:0.2.101
    permissions:
      contents: write
      id-token: write
    env:
      TF_IN_AUTOMATION: 1
    steps:
      - name: git clone
        uses: actions/checkout@v4
      - name: git clone fix
        run: git config --system --add safe.directory $GITHUB_WORKSPACE
      - name: gcloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          create_credentials_file: true
          cleanup_credentials: true
      - name: cache
        uses: actions/cache@v4
        with:
          key: projects-o11y-terraform-submodules-gke-lgtm-stack
          path: |
            projects/o11y/terraform-submodules/gke-lgtm-stack/.terraform
            projects/o11y/terraform-submodules/gke-lgtm-stack/.terraform.lock.hcl
      - name: build
        run: ./scripts/terraform-submodule build "projects/o11y/terraform-submodules/gke-lgtm-stack"
      - name: test
        run: ./scripts/terraform-submodule test "projects/o11y/terraform-submodules/gke-lgtm-stack"
      - name: pre-publish
        if: github.event_name == 'pull_request' && github.base_ref == 'main'
        run: ./scripts/terraform-submodule pre-publish "projects/o11y/terraform-submodules/gke-lgtm-stack"
      - name: publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: ./scripts/terraform-submodule publish "projects/o11y/terraform-submodules/gke-lgtm-stack"
      - name: show
        run: ./scripts/terraform-submodule show "projects/o11y/terraform-submodules/gke-lgtm-stack"
