name: projects/demo/docker-images/kuard
on:
  pull_request:
    paths:
      - "projects/demo/docker-images/kuard/**"
      - "!projects/demo/docker-images/kuard/README.md"
  push:
    branches:
      - main
    paths:
      - "projects/demo/docker-images/kuard/**"
      - "!projects/demo/docker-images/kuard/README.md"
      - "!projects/demo/docker-images/kuard/container-structure-test.yaml"
jobs:
  projects-demo-docker-images-kuard:
    name: projects/demo/docker-images/kuard
    runs-on: ubuntu-24.04
    container: ghcr.io/damlys/gorun-devcontainer:0.2.100
    permissions:
      contents: write
      id-token: write
      packages: write
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: git clone
        uses: actions/checkout@v4
      - name: git clone fix
        run: git config --system --add safe.directory $GITHUB_WORKSPACE
      - name: gcloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          create_credentials_file: true
          cleanup_credentials: true
      - name: docker buildx
        uses: docker/setup-buildx-action@v3
      - name: docker auth (Google Artifact Registry)
        run: gcloud auth configure-docker "europe-central2-docker.pkg.dev"
      - name: docker auth (Docker Hub)
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker auth (GitHub Packages)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: ./scripts/docker-image build "projects/demo/docker-images/kuard"
      - name: test
        run: ./scripts/docker-image test "projects/demo/docker-images/kuard"
      - if: github.event_name == 'pull_request' && github.base_ref == 'main'
        name: pre-publish
        run: ./scripts/docker-image pre-publish "projects/demo/docker-images/kuard"
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        name: publish
        run: ./scripts/docker-image publish "projects/demo/docker-images/kuard"
      - name: show
        run: ./scripts/docker-image show "projects/demo/docker-images/kuard"
