name: projects/demo/terraform-modules/kuard
on:
  pull_request:
    paths:
      - "projects/demo/terraform-modules/kuard/**"
      - "!projects/demo/terraform-modules/kuard/README.md"
  push:
    branches:
      - main
    paths:
      - "projects/demo/terraform-modules/kuard/**"
      - "!projects/demo/terraform-modules/kuard/README.md"
jobs:
  projects-demo-terraform-modules-kuard:
    name: projects/demo/terraform-modules/kuard
    runs-on: ubuntu-24.04
    container: ghcr.io/damlys/gorun-devcontainer:0.2.100
    permissions:
      contents: write
      id-token: write
    env:
      TF_IN_AUTOMATION: 1
    steps:
      - name: git clone
        uses: actions/checkout@v4
      - name: git clone fix
        run: git config --system --add safe.directory $GITHUB_WORKSPACE
      - name: gcloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          create_credentials_file: true
          cleanup_credentials: true
      - name: cache
        uses: actions/cache@v4
        with:
          key: projects-demo-terraform-modules-kuard
          path: |
            projects/demo/terraform-modules/kuard/.terraform
      - name: test
        run: ./scripts/terraform-module test "projects/demo/terraform-modules/kuard"
      - name: init
        run: terraform -chdir="projects/demo/terraform-modules/kuard" init -input=false
      - if: github.event_name == 'pull_request' && github.base_ref == 'main'
        name: plan
        run: terraform -chdir="projects/demo/terraform-modules/kuard" plan -input=false
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        name: apply
        run: terraform -chdir="projects/demo/terraform-modules/kuard" apply -input=false -auto-approve
