name: terraform/submodules/gh-repository
on:
  pull_request:
    paths:
      - "terraform/submodules/gh-repository/**"
      - "!terraform/submodules/gh-repository/README.md"
  push:
    branches:
      - main
    paths:
      - "terraform/submodules/gh-repository/**"
      - "!terraform/submodules/gh-repository/README.md"
jobs:
  terraform-submodules-gh-repository:
    name: terraform/submodules/gh-repository
    runs-on: ubuntu-22.04
    container: ghcr.io/damlys/gorun-devcontainer:0.0.0
    permissions:
      contents: write
      id-token: write
    env:
      GITHUB_OWNER: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_IN_AUTOMATION: 1
    steps:
      - name: git clone
        uses: actions/checkout@v3
      - run: git config --system --add safe.directory /__w/gorun/gorun
      - name: gcloud auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/715614799977/locations/global/workloadIdentityPools/github/providers/github-actions
          service_account: gha-damlys-gorun@gorun-general-2.iam.gserviceaccount.com
          create_credentials_file: true
          export_environment_variables: true
          cleanup_credentials: true
      - name: cache
        uses: actions/cache@v3
        with:
          key: terraform-submodules-gh-repository
          path: |
            terraform/submodules/gh-repository/.terraform
            terraform/submodules/gh-repository/.terraform.lock.hcl
      - name: build
        run: ./scripts/terraform-submodule build "gh-repository"
      - name: test
        run: ./scripts/terraform-submodule test "gh-repository"
      - name: publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: ./scripts/terraform-submodule publish "gh-repository"
      - name: show
        run: ./scripts/terraform-submodule show "gh-repository"
