name: terraform/modules/general-cloud-projects
on:
  pull_request:
    paths:
      - "terraform/modules/general-cloud-projects/**"
      - "!terraform/modules/general-cloud-projects/README.md"
  push:
    branches:
      - main
    paths:
      - "terraform/modules/general-cloud-projects/**"
      - "!terraform/modules/general-cloud-projects/README.md"
jobs:
  terraform-modules-general-cloud-projects:
    name: terraform/modules/general-cloud-projects
    runs-on: ubuntu-22.04
    container: ghcr.io/damlys/gorun-devcontainer:0.0.2
    permissions:
      contents: write
      id-token: write
    env:
      GITHUB_OWNER: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_IN_AUTOMATION: 1
    steps:
      - name: git clone
        uses: actions/checkout@v3
      - run: git config --system --add safe.directory /__w/gorun/gorun
      - name: gcloud auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/715614799977/locations/global/workloadIdentityPools/github/providers/github-actions
          service_account: gha-damlys-gorun@gorun-general-2.iam.gserviceaccount.com
          create_credentials_file: true
          export_environment_variables: true
          cleanup_credentials: true
      - name: cache
        uses: actions/cache@v3
        with:
          key: terraform-modules-general-cloud-projects
          path: |
            terraform/modules/general-cloud-projects/.terraform
      - name: test
        run: ./scripts/terraform-module test "general-cloud-projects"
      - name: fmt check
        run: terraform -chdir="terraform/modules/general-cloud-projects" fmt -check -recursive .
      - name: init
        run: terraform -chdir="terraform/modules/general-cloud-projects" init -input=false
      - name: validate
        run: terraform -chdir="terraform/modules/general-cloud-projects" validate
      - name: plan
        if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main'
        run: terraform -chdir="terraform/modules/general-cloud-projects" plan -input=false
      - name: apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform -chdir="terraform/modules/general-cloud-projects" apply -input=false -auto-approve
