name: test-bash
on:
  pull_request:
    paths:
      - "scripts/**"
  push:
    branches:
      - main
    paths:
      - "scripts/**"
jobs:
  test-bash:
    name: test-bash
    runs-on: ubuntu-24.04
    container: ghcr.io/damlys/gorun-devcontainer:0.4.100
    steps:
      - name: git clone (PR)
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: git clone (not PR)
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v4
      - name: git clone (fix)
        run: git config --system --add safe.directory "$GITHUB_WORKSPACE"
      - name: git config user
        run: git config --global user.name "github-actions" && git config --global user.email "github-actions@github.com"

      - name: format check
        run: shfmt --indent=2 --diff ./scripts
      - name: lint check
        run: shellcheck --exclude=1090 $(find ./scripts -type f)
