name: core-image-node22-sdk
on:
  pull_request:
    paths:
      - "projects/core/docker-images/node22-sdk/**"
      - "!projects/core/docker-images/node22-sdk/README.md"
  push:
    branches:
      - main
    paths:
      - "projects/core/docker-images/node22-sdk/**"
      - "!projects/core/docker-images/node22-sdk/README.md"
      - "!projects/core/docker-images/node22-sdk/container-structure-test.yaml"
jobs:
  core-image-node22-sdk:
    name: core-image-node22-sdk
    runs-on: ubuntu-24.04
    container: ghcr.io/damlys/gorun-devcontainer:0.4.100
    permissions:
      contents: write
      id-token: write
      packages: write
    env:
      DOCKER_BUILDKIT: 1
      HELM_EXPERIMENTAL_OCI: 1
      TF_IN_AUTOMATION: 1
    steps:
      - name: git clone (PR)
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: git clone (not PR)
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v4
      - name: git clone (fix)
        run: git config --system --add safe.directory "$GITHUB_WORKSPACE"
      - name: git config user
        run: git config --global user.name "github-actions" && git config --global user.email "github-actions@github.com"

      - name: gcloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          create_credentials_file: true
          cleanup_credentials: true
      - name: docker buildx
        uses: docker/setup-buildx-action@v3
      - name: docker auth (Google Artifact Registry)
        run: gcloud auth configure-docker "europe-central2-docker.pkg.dev"
      - name: docker auth (Docker Hub)
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker auth (GitHub Packages)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build
        run: ./scripts/docker-image build "projects/core/docker-images/node22-sdk"
      - name: test
        run: ./scripts/docker-image test "projects/core/docker-images/node22-sdk"
      - name: pre-publish
        if: github.event_name == 'pull_request' && github.base_ref == 'main'
        run: ./scripts/docker-image pre-publish "projects/core/docker-images/node22-sdk"
      - name: publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: ./scripts/docker-image publish "projects/core/docker-images/node22-sdk"
      - name: show
        run: ./scripts/docker-image show "projects/core/docker-images/node22-sdk"
