name: demo-gomod-kuard-tester
on:
  pull_request:
    paths:
      - "projects/demo/go-modules/kuard-tester/**"
      - "!projects/demo/go-modules/kuard-tester/README.md"
  push:
    branches:
      - main
    paths:
      - "projects/demo/go-modules/kuard-tester/**"
      - "!projects/demo/go-modules/kuard-tester/README.md"
jobs:
  demo-gomod-kuard-tester:
    name: demo-gomod-kuard-tester
    runs-on: ubuntu-24.04
    container: ghcr.io/damlys/gorun-devcontainer:0.4.100
    permissions:
      contents: write
      id-token: write
    env:
      DOCKER_BUILDKIT: 1
      HELM_EXPERIMENTAL_OCI: 1
      TF_IN_AUTOMATION: 1
    steps:
      - name: git clone (PR)
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: git clone (not PR)
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v4
      - name: git clone (fix)
        run: git config --system --add safe.directory "$GITHUB_WORKSPACE"
      - name: git config user
        run: git config --global user.name "github-actions" && git config --global user.email "github-actions@github.com"

      - name: gcloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          create_credentials_file: true
          cleanup_credentials: true

      - name: test
        run: ./scripts/go-module test "projects/demo/go-modules/kuard-tester"
